project:
  type: book
  output-dir: docs

book:
  title: "ADF&G Division of Sport Fisheries Introduction to Git"
  author: "Adam Reimer"
  date: "6/26/2023"
  chapters:
    - index.qmd
    - intro.Rmd
    - basics.qmd
    - collaboration.qmd
    - intermediate.qmd
  appendices: 
    - RStudio.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-block-border-left: true
    embed-resources: true
  pdf:
    documentclass: scrreprt

editor: visual