project:
  type: book
  output-dir: docs

book:
  title: "ADF&G Division of Sport Fisheries Introduction to Git"
  author: "Adam Reimer"
  date: "7/22/2023"
  chapters:
    - index.qmd
    - intro.Rmd
    - basics.qmd
    - collaboration.qmd
    - branch.qmd
    - history.qmd
    - laststeps.qmd
  appendices: 
    - RStudio.qmd
    - workflow.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    embed-resources: true
    
execute: 
  freeze: auto

editor: visual